### ISSUE TITLE
[BUG] - Game selection is blank

### ISSUE THREAD

**Issue by Mettkrieger** [ebkr/r2modmanPlus#919] opened 2022-12-19 11:41 UTC
**Describe the bug**
After startup of R2ModMan my game selection screen is blank. No game is shown, although at least Valheim is being installed.

**To Reproduce**
1. Start R2ModMan (3.1.34)
2. No game detected

**Expected behavior**
Valheim should be detected

**Screenshots**
[App Screenshot](https://i.imgur.com/joQ9vyj.png)

**Comment by MythicManiac** [comment] 2022-12-20 01:27
Thanks for the report!

Check https://github.com/ebkr/r2modmanPlus/wiki/Error:-White-or-blank-game-select-screen-on-startup

There's a PR also open (#917) for making the workaround easier.

Closing this one as a duplicate of #876

**Closed by MythicManiac** 2022-12-20 01:27 UTC
Labels: bug
