### ISSUE TITLE
[BUG] - r2modman uninstalled itself

### ISSUE THREAD

**Issue by naharamas** [ebkr/r2modmanPlus#1168] opened 2024-01-15 17:54 UTC
**Describe the bug**
After closing r2modman, the desktop icon went blank, trying to open the file location redirected to an empty folder. 

**To Reproduce**
1. Install r2modman 3.1.45 under Program Files (for all users)
2. Open r2modman, get the update notification(for 3.1.46 at this time)
3. Exit r2modman
4. Desktop icon is blank, files are now missing

**Expected behavior**
Applications shouldn't commit seppuku.

**Screenshots**
Not relevant.

**Additional context**
Auto updater probably doesn't get the admin rights properly, the files are deleted but the new ones can't be written, application disappears and must be reinstalled(fortunately, settings and profiles are unaffected since they're in a different folder).
Edit: running on Windows 10.

**Comment by ambalogg** [comment] 2024-01-15 18:06
probably windows defender automatically deleted it

**Comment by naharamas** [comment] 2024-01-15 19:23
> probably windows defender automatically deleted it

No, it can be reproduced even with everything deactivated.

**Comment by ambalogg** [comment] 2024-01-15 20:37
> > probably windows defender automatically deleted it
> 
> No, it can be reproduced even with everything deactivated.

Then Idk bud redownload it

**Comment by GeckoEidechse** [comment] 2024-01-19 14:38
Had the same thing happen. IIRC it was when r2mm prompted an update. Most likely the update process already removed the old files but failed to install the new ones.

Saved mods etc was not affected. When simply re-installing r2mm again, all my past settings were still present ^^

**Comment by VeraxonHD** [comment] 2024-01-24 21:18
Can reproduce, has happened to me twice now

**Comment by Adavee** [comment] 2024-02-21 09:52
Same issue just happened to me.  modman wanted to update when I closed it, all it did was remove it.  I had the same install as @VeraxonHD - installed to Program Files using admin privileges.  Will just install somewhere else and hope that fixes it.  Bit annoying though, I like to keep all my apps in one place.

**Comment by nguyenlamlll** [comment] 2024-04-07 16:28
I'm using 3.1.47 at the moment. 
When I close the app, this fires up. I am not sure where this comes from exactly, but I guess it is in the process of the auto-updater.

![image](https://github.com/ebkr/r2modmanPlus/assets/20963684/730901f5-f641-4c19-aa59-778f71e48cf4)
Pic from my phone because I cannot PrtSc from my computer when that dialog opens.

**Comment by azeunkn0wn** [comment] 2024-04-13 21:28
Ah, so it tried to uninstall itself to update, and probably failed to reinstall? It keeps disappearing on mine as well.

**Comment by ebkr** [comment] 2024-04-14 08:40
See here: https://github.com/ebkr/r2modmanPlus/issues/269#issuecomment-1863387496

**Closed by ebkr** 2024-04-14 08:40 UTC
Labels: bug
