### ISSUE TITLE
[BUG] - Application won't launch on Debian Bookworm without passing '--no-sandbox' or '--in-process-gpu' arguments

### ISSUE THREAD

**Issue by Jimmajones** [ebkr/r2modmanPlus#1258] opened 2024-03-10 00:58 UTC
**Describe the bug**
r2modman will immediately crash when starting on Debian Bookworm. Seems to start fine if either `--no-sandbox` or `--in-process-gpu` are passed as arguments.

**To Reproduce**
1. Attempt to start r2modman. Empty window will briefly show up, then disappear.

**Expected behavior**
Expected r2modman to start.

**Additional context**
Output:
```
$ ./r2modman-3.1.47.AppImage
xdg-settings: default-url-scheme-handler not implemented for xfce
starting server on  /tmp/app.r2mm 
starting TLS server false
starting server as Unix || Windows Socket
[26290:0310/115649.567725:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap
```
Seems to be some sort of Electron issue. See https://github.com/Automattic/simplenote-electron/issues/3096

**Comment by Reonu** [comment] 2024-04-12 18:32
Launching it with the `--no-sandbox` launch argument works as a workaround. I just edited the shortcut.

**Comment by doonv** [comment] 2024-05-10 19:53
This happened to me on Kubuntu, and it continues to happen to me after installing Arch Linux.

Thankfully `--no-sandbox` does fix it on both OSes.

**Comment by ebkr** [comment] 2024-06-18 14:54
Duplicate of #978

**Closed by ebkr** 2024-06-18 14:54 UTC
Labels: bug
