### ISSUE TITLE
[FEATURE REQUEST] - Windows Shortcuts to start a specific profile

### ISSUE THREAD

**Issue by frenchiveruti** [ebkr/r2modmanPlus#456] opened 2021-03-31 23:41 UTC
**What problem does the feature request solve?**
Save a few clicks

**Example mock-up (optional)**
Simply add the posibility to specify a profile in a shortcut, and start r2modman managed game right away. 
Say, 
r2modman.exe  --game "Valheim" --profile "Default"  
That would start Valheim under Default profile.

**Additional information (optional)**
Maybe check for updates of the mods automagically?

**Comment by ebkr** [comment] 2021-04-01 05:37
Hey, this is a duplicate of #448

**Closed by ebkr** 2021-04-01 05:37 UTC
Labels: feature

**Comment by frenchiveruti** [comment] 2021-04-01 12:53
Yes, I saw it today and was like "oh shoot"
